spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    mariadb:
      url: jdbc:mariadb://localhost:3306/travel
      username: root
      password: 1q!1q!
      driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  logging:
    level:
      root: INFO
    file:
      name: logs/myapp.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %class{50}.%M:%line - %msg%n"
      file: "%date{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50}:%line - %msg%n"
    org:
      springframework : DEBUG
      hibernate:
        SQL: DEBUG
        type: descriptor.sql.BasicBinder=TRACE
api-tour:
  serviceKey_De: K9eWaIkQyqUUDZPWH+jI2Br1awNS1WaksaOZ6EiUbWTEzpVBeXnhTuPjni4n6auCsAUANYZ5o3Q89TF0sFU4bA==
  serviceKey_En: K9eWaIkQyqUUDZPWH%2BjI2Br1awNS1WaksaOZ6EiUbWTEzpVBeXnhTuPjni4n6auCsAUANYZ5o3Q89TF0sFU4bA%3D%3D